name: Build, Test, and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run lint
      - run: npm test

  build:
    needs: test # This job will only run if the 'test' job succeeds
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest] # Define the OSes to build
    runs-on: ${{ matrix.os }} # Use the OS from the matrix

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-${{ matrix.os }} # Name the artifact based on the OS
          path: dist/ # The folder where the build output is stored